name: Build LaTeX document
on: [push, workflow_dispatch]

jobs:
  build_latex:
    runs-on: ubuntu-latest    
    container:
      image: ghcr.io/vsht/feyncalc/latex-docker:latest
      credentials:
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        run: |
          latexmk -pdf FeynCalcManual.tex
          echo "DATE_TIME=$(date "+%F %T %Z")" >> $GITHUB_ENV
          echo  "FeynCalc manual (development version). Last update: $(date "+%F %T %Z")" > body.md
      - name: Upload the resulting PDF
        uses: ncipollo/release-action@v1
        with:
          tag: "dev-manual"
          name: "FeynCalc manual (updated on ${{ env.DATE_TIME }})"
          bodyFile: "body.md"
          allowUpdates: true
          artifacts: "FeynCalcManual.pdf,*.aux,*.log"
